spring.application.name=fitzone-backend

# === CONEXIÓN A XAMPP - Base de datos: rubengym ===
spring.datasource.url=jdbc:mysql://localhost:3306/rubengym?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always

# JWT Configuration
jwt.secret=dPX83qK4m2vYj9nB5wL7tF1hR8cA0eW6xZ2sN4gM1bH5yU3pT7kS9vC4uE0iQ6oM8wD2xF5gN1jL3mB7yV9pA4
